/* Christian affiliation estimates, 2020; published by Pew Research Center in 2025.
   Counts rounded to 10,000; countBelow means an upper bound, never an exact count.
   Percentages rounded to 0.1%; bounds preserved. Not estimates for 2026.
   Map label points: Natural Earth (public domain); Channel Islands uses the
   midpoint of the Jersey and Guernsey label points.
   Generated by scripts/update-population-data.cjs. See README for attribution. */
var CHRISTIAN_POPULATION = {
  "year": 2020,
  "published": "2025-06-09",
  "retrieved": "2026-09-25",
  "source": "Pew Research Center",
  "sourceUrl": "https://www.pewresearch.org/religion/feature/religious-composition-by-country-2010-2020/",
  "methodologyUrl": "https://www.pewresearch.org/religion/2025/06/09/global-religious-change-methodology/",
  "sourceScript": "https://www.pewresearch.org/wp-content/plugins/prc-interactive-features/assets/religion/2022/grf-table/build/index.js?ver=a72e5fa308a4ed5192f6",
  "sourceSha256": "22c0f651461e770645d5e67bd8e2a02972770fc3f049740b43b255a1228f5e08",
  "geographySource": "https://www.naturalearthdata.com/",
  "world": {
    "count": 2268860000,
    "countBelow": false,
    "percent": 28.8,
    "percentBound": ""
  },
  "countries": [
    {
      "name": "Afghanistan",
      "region": "Asia-Pacific",
      "count": 10000,
      "countBelow": true,
      "percent": 0.1,
      "percentBound": "<",
      "lat": 34.164,
      "lon": 66.497
    },
    {
      "name": "Albania",
      "region": "Europe",
      "count": 510000,
      "countBelow": false,
      "percent": 17.8,
      "percentBound": "",
      "lat": 40.655,
      "lon": 20.114
    },
    {
      "name": "Algeria",
      "region": "Middle East-North Africa",
      "count": 130000,
      "countBelow": false,
      "percent": 0.3,
      "percentBound": "",
      "lat": 27.397,
      "lon": 2.808
    },
    {
      "name": "Angola",
      "region": "Sub-Saharan Africa",
      "count": 31120000,
      "countBelow": false,
      "percent": 93,
      "percentBound": "",
      "lat": -12.183,
      "lon": 17.984
    },
    {
      "name": "Argentina",
      "region": "Latin America-Caribbean",
      "count": 39970000,
      "countBelow": false,
      "percent": 88.5,
      "percentBound": "",
      "lat": -33.501,
      "lon": -64.173
    },
    {
      "name": "Armenia",
      "region": "Asia-Pacific",
      "count": 2810000,
      "countBelow": false,
      "percent": 97.3,
      "percentBound": "",
      "lat": 40.459,
      "lon": 44.801
    },
    {
      "name": "Aruba",
      "region": "Latin America-Caribbean",
      "count": 90000,
      "countBelow": false,
      "percent": 81.4,
      "percentBound": "",
      "lat": 12.517,
      "lon": -69.973
    },
    {
      "name": "Australia",
      "region": "Asia-Pacific",
      "count": 12040000,
      "countBelow": false,
      "percent": 46.8,
      "percentBound": "",
      "lat": -24.13,
      "lon": 134.05
    },
    {
      "name": "Austria",
      "region": "Europe",
      "count": 6080000,
      "countBelow": false,
      "percent": 68.2,
      "percentBound": "",
      "lat": 47.519,
      "lon": 14.131
    },
    {
      "name": "Azerbaijan",
      "region": "Asia-Pacific",
      "count": 40000,
      "countBelow": false,
      "percent": 0.4,
      "percentBound": "",
      "lat": 40.402,
      "lon": 47.211
    },
    {
      "name": "Bahamas",
      "region": "Latin America-Caribbean",
      "count": 390000,
      "countBelow": false,
      "percent": 97.6,
      "percentBound": "",
      "lat": 26.402,
      "lon": -77.147
    },
    {
      "name": "Bahrain",
      "region": "Middle East-North Africa",
      "count": 200000,
      "countBelow": false,
      "percent": 13.7,
      "percentBound": "",
      "lat": 26.056,
      "lon": 50.555
    },
    {
      "name": "Bangladesh",
      "region": "Asia-Pacific",
      "count": 500000,
      "countBelow": false,
      "percent": 0.3,
      "percentBound": "",
      "lat": 24.215,
      "lon": 89.685
    },
    {
      "name": "Barbados",
      "region": "Latin America-Caribbean",
      "count": 220000,
      "countBelow": false,
      "percent": 77.3,
      "percentBound": "",
      "lat": 13.164,
      "lon": -59.569
    },
    {
      "name": "Belarus",
      "region": "Europe",
      "count": 7960000,
      "countBelow": false,
      "percent": 85.1,
      "percentBound": "",
      "lat": 53.822,
      "lon": 28.418
    },
    {
      "name": "Belgium",
      "region": "Europe",
      "count": 5880000,
      "countBelow": false,
      "percent": 51,
      "percentBound": "",
      "lat": 50.785,
      "lon": 4.8
    },
    {
      "name": "Belize",
      "region": "Latin America-Caribbean",
      "count": 290000,
      "countBelow": false,
      "percent": 74.4,
      "percentBound": "",
      "lat": 17.202,
      "lon": -88.713
    },
    {
      "name": "Benin",
      "region": "Sub-Saharan Africa",
      "count": 6960000,
      "countBelow": false,
      "percent": 53.2,
      "percentBound": "",
      "lat": 10.325,
      "lon": 2.352
    },
    {
      "name": "Bhutan",
      "region": "Asia-Pacific",
      "count": 10000,
      "countBelow": true,
      "percent": 0.6,
      "percentBound": "",
      "lat": 27.537,
      "lon": 90.04
    },
    {
      "name": "Bolivia",
      "region": "Latin America-Caribbean",
      "count": 10510000,
      "countBelow": false,
      "percent": 88.9,
      "percentBound": "",
      "lat": -16.666,
      "lon": -64.593
    },
    {
      "name": "Bosnia and Herzegovina",
      "region": "Europe",
      "count": 1470000,
      "countBelow": false,
      "percent": 44.7,
      "percentBound": "",
      "lat": 44.091,
      "lon": 18.068
    },
    {
      "name": "Botswana",
      "region": "Sub-Saharan Africa",
      "count": 1950000,
      "countBelow": false,
      "percent": 82.3,
      "percentBound": "",
      "lat": -22.103,
      "lon": 24.179
    },
    {
      "name": "Brazil",
      "region": "Latin America-Caribbean",
      "count": 168300000,
      "countBelow": false,
      "percent": 80.7,
      "percentBound": "",
      "lat": -12.099,
      "lon": -49.559
    },
    {
      "name": "Brunei",
      "region": "Asia-Pacific",
      "count": 30000,
      "countBelow": false,
      "percent": 6.7,
      "percentBound": "",
      "lat": 4.448,
      "lon": 114.552
    },
    {
      "name": "Bulgaria",
      "region": "Europe",
      "count": 5510000,
      "countBelow": false,
      "percent": 79.5,
      "percentBound": "",
      "lat": 42.509,
      "lon": 25.157
    },
    {
      "name": "Burkina Faso",
      "region": "Sub-Saharan Africa",
      "count": 6010000,
      "countBelow": false,
      "percent": 28,
      "percentBound": "",
      "lat": 12.673,
      "lon": -1.364
    },
    {
      "name": "Burundi",
      "region": "Sub-Saharan Africa",
      "count": 11980000,
      "countBelow": false,
      "percent": 95,
      "percentBound": "",
      "lat": -3.333,
      "lon": 29.917
    },
    {
      "name": "Cambodia",
      "region": "Asia-Pacific",
      "count": 50000,
      "countBelow": false,
      "percent": 0.3,
      "percentBound": "",
      "lat": 12.648,
      "lon": 104.505
    },
    {
      "name": "Cameroon",
      "region": "Sub-Saharan Africa",
      "count": 18300000,
      "countBelow": false,
      "percent": 69.8,
      "percentBound": "",
      "lat": 4.585,
      "lon": 12.473
    },
    {
      "name": "Canada",
      "region": "North America",
      "count": 20350000,
      "countBelow": false,
      "percent": 53.3,
      "percentBound": "",
      "lat": 60.324,
      "lon": -101.911
    },
    {
      "name": "Cape Verde",
      "region": "Sub-Saharan Africa",
      "count": 400000,
      "countBelow": false,
      "percent": 78.3,
      "percentBound": "",
      "lat": 15.075,
      "lon": -23.639
    },
    {
      "name": "Central African Republic",
      "region": "Sub-Saharan Africa",
      "count": 4560000,
      "countBelow": false,
      "percent": 90.7,
      "percentBound": "",
      "lat": 6.99,
      "lon": 20.907
    },
    {
      "name": "Chad",
      "region": "Sub-Saharan Africa",
      "count": 6700000,
      "countBelow": false,
      "percent": 38.9,
      "percentBound": "",
      "lat": 15.143,
      "lon": 18.645
    },
    {
      "name": "Channel Islands",
      "region": "Europe",
      "count": 140000,
      "countBelow": false,
      "percent": 85.2,
      "percentBound": "",
      "lat": 49.342,
      "lon": -2.326
    },
    {
      "name": "Chile",
      "region": "Latin America-Caribbean",
      "count": 13240000,
      "countBelow": false,
      "percent": 68.3,
      "percentBound": "",
      "lat": -38.152,
      "lon": -72.319
    },
    {
      "name": "China",
      "region": "Asia-Pacific",
      "count": 25450000,
      "countBelow": false,
      "percent": 1.8,
      "percentBound": "",
      "lat": 32.498,
      "lon": 106.337
    },
    {
      "name": "Colombia",
      "region": "Latin America-Caribbean",
      "count": 43670000,
      "countBelow": false,
      "percent": 86.2,
      "percentBound": "",
      "lat": 3.373,
      "lon": -73.174
    },
    {
      "name": "Comoros",
      "region": "Sub-Saharan Africa",
      "count": 10000,
      "countBelow": true,
      "percent": 0.5,
      "percentBound": "",
      "lat": -11.728,
      "lon": 43.318
    },
    {
      "name": "Costa Rica",
      "region": "Latin America-Caribbean",
      "count": 4420000,
      "countBelow": false,
      "percent": 87.9,
      "percentBound": "",
      "lat": 10.065,
      "lon": -84.078
    },
    {
      "name": "Croatia",
      "region": "Europe",
      "count": 3590000,
      "countBelow": false,
      "percent": 90.9,
      "percentBound": "",
      "lat": 45.806,
      "lon": 16.372
    },
    {
      "name": "Cuba",
      "region": "Latin America-Caribbean",
      "count": 6780000,
      "countBelow": false,
      "percent": 60.7,
      "percentBound": "",
      "lat": 21.334,
      "lon": -77.976
    },
    {
      "name": "Curacao",
      "region": "Latin America-Caribbean",
      "count": 170000,
      "countBelow": false,
      "percent": 90.6,
      "percentBound": "",
      "lat": 12.145,
      "lon": -68.921
    },
    {
      "name": "Cyprus",
      "region": "Asia-Pacific",
      "count": 880000,
      "countBelow": false,
      "percent": 67.7,
      "percentBound": "",
      "lat": 34.913,
      "lon": 33.084
    },
    {
      "name": "Czech Republic",
      "region": "Europe",
      "count": 2790000,
      "countBelow": false,
      "percent": 26.4,
      "percentBound": "",
      "lat": 49.882,
      "lon": 15.378
    },
    {
      "name": "Democratic Republic of the Congo",
      "region": "Sub-Saharan Africa",
      "count": 92400000,
      "countBelow": false,
      "percent": 96.3,
      "percentBound": "",
      "lat": -1.858,
      "lon": 23.459
    },
    {
      "name": "Denmark",
      "region": "Europe",
      "count": 4480000,
      "countBelow": false,
      "percent": 76.9,
      "percentBound": "",
      "lat": 55.967,
      "lon": 9.018
    },
    {
      "name": "Djibouti",
      "region": "Sub-Saharan Africa",
      "count": 10000,
      "countBelow": false,
      "percent": 1.1,
      "percentBound": "",
      "lat": 11.976,
      "lon": 42.499
    },
    {
      "name": "Dominican Republic",
      "region": "Latin America-Caribbean",
      "count": 8550000,
      "countBelow": false,
      "percent": 77.6,
      "percentBound": "",
      "lat": 19.104,
      "lon": -70.654
    },
    {
      "name": "Ecuador",
      "region": "Latin America-Caribbean",
      "count": 15530000,
      "countBelow": false,
      "percent": 88.5,
      "percentBound": "",
      "lat": -1.259,
      "lon": -78.188
    },
    {
      "name": "Egypt",
      "region": "Middle East-North Africa",
      "count": 5270000,
      "countBelow": false,
      "percent": 4.8,
      "percentBound": "",
      "lat": 26.186,
      "lon": 29.446
    },
    {
      "name": "El Salvador",
      "region": "Latin America-Caribbean",
      "count": 5430000,
      "countBelow": false,
      "percent": 87.1,
      "percentBound": "",
      "lat": 13.685,
      "lon": -88.89
    },
    {
      "name": "Equatorial Guinea",
      "region": "Sub-Saharan Africa",
      "count": 1520000,
      "countBelow": false,
      "percent": 88.7,
      "percentBound": "",
      "lat": 2.333,
      "lon": 8.99
    },
    {
      "name": "Eritrea",
      "region": "Sub-Saharan Africa",
      "count": 1540000,
      "countBelow": false,
      "percent": 46.7,
      "percentBound": "",
      "lat": 15.787,
      "lon": 38.286
    },
    {
      "name": "Estonia",
      "region": "Europe",
      "count": 700000,
      "countBelow": false,
      "percent": 52.6,
      "percentBound": "",
      "lat": 58.725,
      "lon": 25.867
    },
    {
      "name": "Eswatini",
      "region": "Sub-Saharan Africa",
      "count": 1110000,
      "countBelow": false,
      "percent": 93.2,
      "percentBound": "",
      "lat": -26.534,
      "lon": 31.467
    },
    {
      "name": "Ethiopia",
      "region": "Sub-Saharan Africa",
      "count": 73230000,
      "countBelow": false,
      "percent": 61.6,
      "percentBound": "",
      "lat": 8.033,
      "lon": 39.089
    },
    {
      "name": "Federated States of Micronesia",
      "region": "Asia-Pacific",
      "count": 110000,
      "countBelow": false,
      "percent": 98.8,
      "percentBound": "",
      "lat": 6.888,
      "lon": 158.234
    },
    {
      "name": "Fiji",
      "region": "Asia-Pacific",
      "count": 640000,
      "countBelow": false,
      "percent": 69.5,
      "percentBound": "",
      "lat": -17.826,
      "lon": 177.975
    },
    {
      "name": "Finland",
      "region": "Europe",
      "count": 4000000,
      "countBelow": false,
      "percent": 72.3,
      "percentBound": "",
      "lat": 63.252,
      "lon": 27.276
    },
    {
      "name": "France",
      "region": "Europe",
      "count": 30620000,
      "countBelow": false,
      "percent": 46.5,
      "percentBound": "",
      "lat": 46.696,
      "lon": 2.552
    },
    {
      "name": "French Guiana",
      "region": "Latin America-Caribbean",
      "count": 240000,
      "countBelow": false,
      "percent": 84.2,
      "percentBound": "",
      "lat": 3.999,
      "lon": -53.068
    },
    {
      "name": "French Polynesia",
      "region": "Asia-Pacific",
      "count": 260000,
      "countBelow": false,
      "percent": 93.4,
      "percentBound": "",
      "lat": -17.628,
      "lon": -149.462
    },
    {
      "name": "Gabon",
      "region": "Sub-Saharan Africa",
      "count": 1940000,
      "countBelow": false,
      "percent": 83.7,
      "percentBound": "",
      "lat": -0.438,
      "lon": 11.836
    },
    {
      "name": "Gambia",
      "region": "Sub-Saharan Africa",
      "count": 70000,
      "countBelow": false,
      "percent": 2.9,
      "percentBound": "",
      "lat": 13.642,
      "lon": -14.998
    },
    {
      "name": "Georgia",
      "region": "Europe",
      "count": 3350000,
      "countBelow": false,
      "percent": 88.2,
      "percentBound": "",
      "lat": 41.87,
      "lon": 43.736
    },
    {
      "name": "Germany",
      "region": "Europe",
      "count": 47030000,
      "countBelow": false,
      "percent": 56.2,
      "percentBound": "",
      "lat": 50.962,
      "lon": 9.678
    },
    {
      "name": "Ghana",
      "region": "Sub-Saharan Africa",
      "count": 22730000,
      "countBelow": false,
      "percent": 71.3,
      "percentBound": "",
      "lat": 7.718,
      "lon": -1.037
    },
    {
      "name": "Greece",
      "region": "Europe",
      "count": 9570000,
      "countBelow": false,
      "percent": 89.5,
      "percentBound": "",
      "lat": 39.493,
      "lon": 21.726
    },
    {
      "name": "Grenada",
      "region": "Latin America-Caribbean",
      "count": 100000,
      "countBelow": false,
      "percent": 87.5,
      "percentBound": "",
      "lat": 12.113,
      "lon": -61.68
    },
    {
      "name": "Guadeloupe",
      "region": "Latin America-Caribbean",
      "count": 390000,
      "countBelow": false,
      "percent": 95.9,
      "percentBound": "",
      "lat": 16.299,
      "lon": -61.434
    },
    {
      "name": "Guam",
      "region": "Asia-Pacific",
      "count": 150000,
      "countBelow": false,
      "percent": 94,
      "percentBound": "",
      "lat": 13.354,
      "lon": 144.704
    },
    {
      "name": "Guatemala",
      "region": "Latin America-Caribbean",
      "count": 15960000,
      "countBelow": false,
      "percent": 92,
      "percentBound": "",
      "lat": 14.982,
      "lon": -90.497
    },
    {
      "name": "Guinea",
      "region": "Sub-Saharan Africa",
      "count": 1570000,
      "countBelow": false,
      "percent": 11.7,
      "percentBound": "",
      "lat": 10.619,
      "lon": -10.016
    },
    {
      "name": "Guinea-Bissau",
      "region": "Sub-Saharan Africa",
      "count": 440000,
      "countBelow": false,
      "percent": 21.7,
      "percentBound": "",
      "lat": 12.164,
      "lon": -14.524
    },
    {
      "name": "Guyana",
      "region": "Latin America-Caribbean",
      "count": 530000,
      "countBelow": false,
      "percent": 65.9,
      "percentBound": "",
      "lat": 5.124,
      "lon": -58.943
    },
    {
      "name": "Haiti",
      "region": "Latin America-Caribbean",
      "count": 9980000,
      "countBelow": false,
      "percent": 88.7,
      "percentBound": "",
      "lat": 19.264,
      "lon": -72.224
    },
    {
      "name": "Honduras",
      "region": "Latin America-Caribbean",
      "count": 8950000,
      "countBelow": false,
      "percent": 88.5,
      "percentBound": "",
      "lat": 14.795,
      "lon": -86.888
    },
    {
      "name": "Hong Kong",
      "region": "Asia-Pacific",
      "count": 1400000,
      "countBelow": false,
      "percent": 18.7,
      "percentBound": "",
      "lat": 22.449,
      "lon": 114.098
    },
    {
      "name": "Hungary",
      "region": "Europe",
      "count": 7060000,
      "countBelow": false,
      "percent": 72.4,
      "percentBound": "",
      "lat": 47.087,
      "lon": 19.448
    },
    {
      "name": "Iceland",
      "region": "Europe",
      "count": 270000,
      "countBelow": false,
      "percent": 74.9,
      "percentBound": "",
      "lat": 64.779,
      "lon": -18.674
    },
    {
      "name": "India",
      "region": "Asia-Pacific",
      "count": 31060000,
      "countBelow": false,
      "percent": 2.2,
      "percentBound": "",
      "lat": 22.687,
      "lon": 79.358
    },
    {
      "name": "Indonesia",
      "region": "Asia-Pacific",
      "count": 28200000,
      "countBelow": false,
      "percent": 10.3,
      "percentBound": "",
      "lat": -0.954,
      "lon": 101.893
    },
    {
      "name": "Iran",
      "region": "Asia-Pacific",
      "count": 130000,
      "countBelow": false,
      "percent": 0.1,
      "percentBound": "",
      "lat": 32.166,
      "lon": 54.931
    },
    {
      "name": "Iraq",
      "region": "Middle East-North Africa",
      "count": 160000,
      "countBelow": false,
      "percent": 0.4,
      "percentBound": "",
      "lat": 33.094,
      "lon": 43.262
    },
    {
      "name": "Ireland",
      "region": "Europe",
      "count": 4050000,
      "countBelow": false,
      "percent": 81.2,
      "percentBound": "",
      "lat": 53.079,
      "lon": -7.799
    },
    {
      "name": "Israel",
      "region": "Middle East-North Africa",
      "count": 170000,
      "countBelow": false,
      "percent": 1.9,
      "percentBound": "",
      "lat": 30.911,
      "lon": 34.848
    },
    {
      "name": "Italy",
      "region": "Europe",
      "count": 48210000,
      "countBelow": false,
      "percent": 80.5,
      "percentBound": "",
      "lat": 44.732,
      "lon": 11.077
    },
    {
      "name": "Ivory Coast",
      "region": "Sub-Saharan Africa",
      "count": 12990000,
      "countBelow": false,
      "percent": 44.9,
      "percentBound": "",
      "lat": 7.491,
      "lon": -5.569
    },
    {
      "name": "Jamaica",
      "region": "Latin America-Caribbean",
      "count": 1940000,
      "countBelow": false,
      "percent": 68.6,
      "percentBound": "",
      "lat": 18.137,
      "lon": -77.319
    },
    {
      "name": "Japan",
      "region": "Asia-Pacific",
      "count": 2840000,
      "countBelow": false,
      "percent": 2.2,
      "percentBound": "",
      "lat": 36.143,
      "lon": 138.442
    },
    {
      "name": "Jordan",
      "region": "Middle East-North Africa",
      "count": 310000,
      "countBelow": false,
      "percent": 2.8,
      "percentBound": "",
      "lat": 30.805,
      "lon": 36.376
    },
    {
      "name": "Kazakhstan",
      "region": "Asia-Pacific",
      "count": 3760000,
      "countBelow": false,
      "percent": 19.3,
      "percentBound": "",
      "lat": 49.054,
      "lon": 68.686
    },
    {
      "name": "Kenya",
      "region": "Sub-Saharan Africa",
      "count": 44730000,
      "countBelow": false,
      "percent": 85.7,
      "percentBound": "",
      "lat": 0.549,
      "lon": 37.908
    },
    {
      "name": "Kiribati",
      "region": "Asia-Pacific",
      "count": 120000,
      "countBelow": false,
      "percent": 97.6,
      "percentBound": "",
      "lat": 1.82,
      "lon": -157.385
    },
    {
      "name": "Kosovo",
      "region": "Europe",
      "count": 100000,
      "countBelow": false,
      "percent": 5.6,
      "percentBound": "",
      "lat": 42.594,
      "lon": 20.861
    },
    {
      "name": "Kuwait",
      "region": "Middle East-North Africa",
      "count": 460000,
      "countBelow": false,
      "percent": 10.5,
      "percentBound": "",
      "lat": 29.414,
      "lon": 47.314
    },
    {
      "name": "Kyrgyzstan",
      "region": "Asia-Pacific",
      "count": 380000,
      "countBelow": false,
      "percent": 5.8,
      "percentBound": "",
      "lat": 41.669,
      "lon": 74.533
    },
    {
      "name": "Laos",
      "region": "Asia-Pacific",
      "count": 110000,
      "countBelow": false,
      "percent": 1.5,
      "percentBound": "",
      "lat": 19.432,
      "lon": 102.534
    },
    {
      "name": "Latvia",
      "region": "Europe",
      "count": 1470000,
      "countBelow": false,
      "percent": 77.3,
      "percentBound": "",
      "lat": 57.067,
      "lon": 25.459
    },
    {
      "name": "Lebanon",
      "region": "Middle East-North Africa",
      "count": 1590000,
      "countBelow": false,
      "percent": 27.9,
      "percentBound": "",
      "lat": 34.133,
      "lon": 35.993
    },
    {
      "name": "Lesotho",
      "region": "Sub-Saharan Africa",
      "count": 2180000,
      "countBelow": false,
      "percent": 97.3,
      "percentBound": "",
      "lat": -29.48,
      "lon": 28.247
    },
    {
      "name": "Liberia",
      "region": "Sub-Saharan Africa",
      "count": 4390000,
      "countBelow": false,
      "percent": 85.2,
      "percentBound": "",
      "lat": 6.447,
      "lon": -9.46
    },
    {
      "name": "Libya",
      "region": "Middle East-North Africa",
      "count": 40000,
      "countBelow": false,
      "percent": 0.5,
      "percentBound": "",
      "lat": 26.639,
      "lon": 18.011
    },
    {
      "name": "Lithuania",
      "region": "Europe",
      "count": 2580000,
      "countBelow": false,
      "percent": 92.2,
      "percentBound": "",
      "lat": 55.104,
      "lon": 24.09
    },
    {
      "name": "Luxembourg",
      "region": "Europe",
      "count": 420000,
      "countBelow": false,
      "percent": 65.9,
      "percentBound": "",
      "lat": 49.734,
      "lon": 6.078
    },
    {
      "name": "Macao",
      "region": "Asia-Pacific",
      "count": 70000,
      "countBelow": false,
      "percent": 10.1,
      "percentBound": "",
      "lat": 22.13,
      "lon": 113.556
    },
    {
      "name": "Madagascar",
      "region": "Sub-Saharan Africa",
      "count": 21490000,
      "countBelow": false,
      "percent": 74.2,
      "percentBound": "",
      "lat": -18.628,
      "lon": 46.704
    },
    {
      "name": "Malawi",
      "region": "Sub-Saharan Africa",
      "count": 17070000,
      "countBelow": false,
      "percent": 87.4,
      "percentBound": "",
      "lat": -13.387,
      "lon": 33.608
    },
    {
      "name": "Malaysia",
      "region": "Asia-Pacific",
      "count": 3100000,
      "countBelow": false,
      "percent": 9.2,
      "percentBound": "",
      "lat": 2.529,
      "lon": 113.837
    },
    {
      "name": "Maldives",
      "region": "Asia-Pacific",
      "count": 10000,
      "countBelow": true,
      "percent": 1.6,
      "percentBound": "",
      "lat": 4.174,
      "lon": 73.508
    },
    {
      "name": "Mali",
      "region": "Sub-Saharan Africa",
      "count": 560000,
      "countBelow": false,
      "percent": 2.6,
      "percentBound": "",
      "lat": 18.693,
      "lon": -2.038
    },
    {
      "name": "Malta",
      "region": "Europe",
      "count": 460000,
      "countBelow": false,
      "percent": 88.6,
      "percentBound": "",
      "lat": 35.893,
      "lon": 14.433
    },
    {
      "name": "Martinique",
      "region": "Latin America-Caribbean",
      "count": 340000,
      "countBelow": false,
      "percent": 96,
      "percentBound": "",
      "lat": 14.712,
      "lon": -61.056
    },
    {
      "name": "Mauritania",
      "region": "Sub-Saharan Africa",
      "count": 10000,
      "countBelow": false,
      "percent": 0.2,
      "percentBound": "",
      "lat": 19.587,
      "lon": -9.74
    },
    {
      "name": "Mauritius",
      "region": "Sub-Saharan Africa",
      "count": 420000,
      "countBelow": false,
      "percent": 32.9,
      "percentBound": "",
      "lat": -20.3,
      "lon": 57.566
    },
    {
      "name": "Mayotte",
      "region": "Sub-Saharan Africa",
      "count": 10000,
      "countBelow": true,
      "percent": 0.5,
      "percentBound": "",
      "lat": -12.775,
      "lon": 45.151
    },
    {
      "name": "Mexico",
      "region": "Latin America-Caribbean",
      "count": 113070000,
      "countBelow": false,
      "percent": 89.2,
      "percentBound": "",
      "lat": 23.92,
      "lon": -102.289
    },
    {
      "name": "Moldova",
      "region": "Europe",
      "count": 3050000,
      "countBelow": false,
      "percent": 99.5,
      "percentBound": "",
      "lat": 47.435,
      "lon": 28.488
    },
    {
      "name": "Mongolia",
      "region": "Asia-Pacific",
      "count": 40000,
      "countBelow": false,
      "percent": 1.3,
      "percentBound": "",
      "lat": 45.997,
      "lon": 104.15
    },
    {
      "name": "Montenegro",
      "region": "Europe",
      "count": 460000,
      "countBelow": false,
      "percent": 76,
      "percentBound": "",
      "lat": 42.803,
      "lon": 19.144
    },
    {
      "name": "Morocco",
      "region": "Middle East-North Africa",
      "count": 30000,
      "countBelow": false,
      "percent": 0.1,
      "percentBound": "<",
      "lat": 31.651,
      "lon": -7.187
    },
    {
      "name": "Mozambique",
      "region": "Sub-Saharan Africa",
      "count": 18880000,
      "countBelow": false,
      "percent": 61.3,
      "percentBound": "",
      "lat": -13.943,
      "lon": 37.838
    },
    {
      "name": "Myanmar",
      "region": "Asia-Pacific",
      "count": 3250000,
      "countBelow": false,
      "percent": 6.1,
      "percentBound": "",
      "lat": 21.574,
      "lon": 95.804
    },
    {
      "name": "Namibia",
      "region": "Sub-Saharan Africa",
      "count": 2470000,
      "countBelow": false,
      "percent": 90.5,
      "percentBound": "",
      "lat": -20.575,
      "lon": 17.108
    },
    {
      "name": "Nepal",
      "region": "Asia-Pacific",
      "count": 510000,
      "countBelow": false,
      "percent": 1.8,
      "percentBound": "",
      "lat": 28.298,
      "lon": 83.64
    },
    {
      "name": "Netherlands",
      "region": "Europe",
      "count": 6190000,
      "countBelow": false,
      "percent": 35.1,
      "percentBound": "",
      "lat": 52.422,
      "lon": 5.611
    },
    {
      "name": "New Caledonia",
      "region": "Asia-Pacific",
      "count": 240000,
      "countBelow": false,
      "percent": 85.1,
      "percentBound": "",
      "lat": -21.065,
      "lon": 165.084
    },
    {
      "name": "New Zealand",
      "region": "Asia-Pacific",
      "count": 2040000,
      "countBelow": false,
      "percent": 40.3,
      "percentBound": "",
      "lat": -39.759,
      "lon": 172.787
    },
    {
      "name": "Nicaragua",
      "region": "Latin America-Caribbean",
      "count": 5570000,
      "countBelow": false,
      "percent": 84.8,
      "percentBound": "",
      "lat": 12.671,
      "lon": -85.069
    },
    {
      "name": "Niger",
      "region": "Sub-Saharan Africa",
      "count": 130000,
      "countBelow": false,
      "percent": 0.6,
      "percentBound": "",
      "lat": 17.446,
      "lon": 9.504
    },
    {
      "name": "Nigeria",
      "region": "Sub-Saharan Africa",
      "count": 92770000,
      "countBelow": false,
      "percent": 43.4,
      "percentBound": "",
      "lat": 9.44,
      "lon": 7.503
    },
    {
      "name": "North Korea",
      "region": "Asia-Pacific",
      "count": 100000,
      "countBelow": false,
      "percent": 0.4,
      "percentBound": "",
      "lat": 39.885,
      "lon": 126.445
    },
    {
      "name": "North Macedonia",
      "region": "Europe",
      "count": 1210000,
      "countBelow": false,
      "percent": 64.7,
      "percentBound": "",
      "lat": 41.558,
      "lon": 21.556
    },
    {
      "name": "Norway",
      "region": "Europe",
      "count": 3840000,
      "countBelow": false,
      "percent": 71.4,
      "percentBound": "",
      "lat": 61.357,
      "lon": 9.68
    },
    {
      "name": "Oman",
      "region": "Middle East-North Africa",
      "count": 370000,
      "countBelow": false,
      "percent": 8.1,
      "percentBound": "",
      "lat": 22.12,
      "lon": 57.337
    },
    {
      "name": "Pakistan",
      "region": "Asia-Pacific",
      "count": 2990000,
      "countBelow": false,
      "percent": 1.3,
      "percentBound": "",
      "lat": 29.328,
      "lon": 68.546
    },
    {
      "name": "Palestinian territories",
      "region": "Middle East-North Africa",
      "count": 50000,
      "countBelow": false,
      "percent": 1,
      "percentBound": "",
      "lat": 32.047,
      "lon": 35.291
    },
    {
      "name": "Panama",
      "region": "Latin America-Caribbean",
      "count": 3910000,
      "countBelow": false,
      "percent": 91.2,
      "percentBound": "",
      "lat": 8.722,
      "lon": -80.352
    },
    {
      "name": "Papua New Guinea",
      "region": "Asia-Pacific",
      "count": 9730000,
      "countBelow": false,
      "percent": 99.1,
      "percentBound": "",
      "lat": -5.695,
      "lon": 143.91
    },
    {
      "name": "Paraguay",
      "region": "Latin America-Caribbean",
      "count": 6180000,
      "countBelow": false,
      "percent": 93.5,
      "percentBound": "",
      "lat": -21.675,
      "lon": -60.146
    },
    {
      "name": "Peru",
      "region": "Latin America-Caribbean",
      "count": 31030000,
      "countBelow": false,
      "percent": 94.5,
      "percentBound": "",
      "lat": -12.977,
      "lon": -72.9
    },
    {
      "name": "Philippines",
      "region": "Asia-Pacific",
      "count": 102510000,
      "countBelow": false,
      "percent": 91.5,
      "percentBound": "",
      "lat": 11.198,
      "lon": 122.465
    },
    {
      "name": "Poland",
      "region": "Europe",
      "count": 34810000,
      "countBelow": false,
      "percent": 91.2,
      "percentBound": "",
      "lat": 51.99,
      "lon": 19.49
    },
    {
      "name": "Portugal",
      "region": "Europe",
      "count": 8820000,
      "countBelow": false,
      "percent": 85.1,
      "percentBound": "",
      "lat": 39.607,
      "lon": -8.272
    },
    {
      "name": "Puerto Rico",
      "region": "Latin America-Caribbean",
      "count": 2910000,
      "countBelow": false,
      "percent": 88.8,
      "percentBound": "",
      "lat": 18.235,
      "lon": -66.481
    },
    {
      "name": "Qatar",
      "region": "Middle East-North Africa",
      "count": 350000,
      "countBelow": false,
      "percent": 12.5,
      "percentBound": "",
      "lat": 25.237,
      "lon": 51.144
    },
    {
      "name": "Republic of the Congo",
      "region": "Sub-Saharan Africa",
      "count": 5310000,
      "countBelow": false,
      "percent": 92.2,
      "percentBound": "",
      "lat": 0.142,
      "lon": 15.901
    },
    {
      "name": "Reunion",
      "region": "Sub-Saharan Africa",
      "count": 750000,
      "countBelow": false,
      "percent": 87.5,
      "percentBound": "",
      "lat": -21.113,
      "lon": 55.536
    },
    {
      "name": "Romania",
      "region": "Europe",
      "count": 19110000,
      "countBelow": false,
      "percent": 98.5,
      "percentBound": "",
      "lat": 45.733,
      "lon": 24.973
    },
    {
      "name": "Russia",
      "region": "Europe",
      "count": 102350000,
      "countBelow": false,
      "percent": 69.9,
      "percentBound": "",
      "lat": 58.249,
      "lon": 44.686
    },
    {
      "name": "Rwanda",
      "region": "Sub-Saharan Africa",
      "count": 12680000,
      "countBelow": false,
      "percent": 97,
      "percentBound": "",
      "lat": -1.897,
      "lon": 30.104
    },
    {
      "name": "Samoa",
      "region": "Asia-Pacific",
      "count": 210000,
      "countBelow": false,
      "percent": 97.6,
      "percentBound": "",
      "lat": -13.639,
      "lon": -172.438
    },
    {
      "name": "São Tomé and Príncipe",
      "region": "Sub-Saharan Africa",
      "count": 180000,
      "countBelow": false,
      "percent": 84.4,
      "percentBound": "",
      "lat": 0.971,
      "lon": 7.021
    },
    {
      "name": "Saudi Arabia",
      "region": "Middle East-North Africa",
      "count": 1360000,
      "countBelow": false,
      "percent": 4.4,
      "percentBound": "",
      "lat": 23.807,
      "lon": 44.7
    },
    {
      "name": "Senegal",
      "region": "Sub-Saharan Africa",
      "count": 400000,
      "countBelow": false,
      "percent": 2.4,
      "percentBound": "",
      "lat": 15.138,
      "lon": -14.779
    },
    {
      "name": "Serbia",
      "region": "Europe",
      "count": 6320000,
      "countBelow": false,
      "percent": 91.5,
      "percentBound": "",
      "lat": 44.19,
      "lon": 20.788
    },
    {
      "name": "Seychelles",
      "region": "Sub-Saharan Africa",
      "count": 110000,
      "countBelow": false,
      "percent": 94,
      "percentBound": "",
      "lat": -4.677,
      "lon": 55.48
    },
    {
      "name": "Sierra Leone",
      "region": "Sub-Saharan Africa",
      "count": 1570000,
      "countBelow": false,
      "percent": 19.8,
      "percentBound": "",
      "lat": 8.617,
      "lon": -11.764
    },
    {
      "name": "Singapore",
      "region": "Asia-Pacific",
      "count": 1050000,
      "countBelow": false,
      "percent": 18.8,
      "percentBound": "",
      "lat": 1.367,
      "lon": 103.817
    },
    {
      "name": "Slovakia",
      "region": "Europe",
      "count": 4020000,
      "countBelow": false,
      "percent": 73.7,
      "percentBound": "",
      "lat": 48.734,
      "lon": 19.05
    },
    {
      "name": "Slovenia",
      "region": "Europe",
      "count": 1380000,
      "countBelow": false,
      "percent": 65.4,
      "percentBound": "",
      "lat": 46.061,
      "lon": 14.915
    },
    {
      "name": "Solomon Islands",
      "region": "Asia-Pacific",
      "count": 710000,
      "countBelow": false,
      "percent": 95,
      "percentBound": "",
      "lat": -8.03,
      "lon": 159.17
    },
    {
      "name": "Somalia",
      "region": "Sub-Saharan Africa",
      "count": 10000,
      "countBelow": true,
      "percent": 0.1,
      "percentBound": "<",
      "lat": 3.569,
      "lon": 45.192
    },
    {
      "name": "South Africa",
      "region": "Sub-Saharan Africa",
      "count": 51630000,
      "countBelow": false,
      "percent": 85.3,
      "percentBound": "",
      "lat": -29.709,
      "lon": 23.666
    },
    {
      "name": "South Korea",
      "region": "Asia-Pacific",
      "count": 16590000,
      "countBelow": false,
      "percent": 32,
      "percentBound": "",
      "lat": 36.385,
      "lon": 128.13
    },
    {
      "name": "South Sudan",
      "region": "Sub-Saharan Africa",
      "count": 6470000,
      "countBelow": false,
      "percent": 60.5,
      "percentBound": "",
      "lat": 7.23,
      "lon": 30.39
    },
    {
      "name": "Spain",
      "region": "Europe",
      "count": 33120000,
      "countBelow": false,
      "percent": 69.5,
      "percentBound": "",
      "lat": 40.091,
      "lon": -3.465
    },
    {
      "name": "Sri Lanka",
      "region": "Asia-Pacific",
      "count": 1260000,
      "countBelow": false,
      "percent": 5.6,
      "percentBound": "",
      "lat": 7.581,
      "lon": 80.705
    },
    {
      "name": "St. Lucia",
      "region": "Latin America-Caribbean",
      "count": 160000,
      "countBelow": false,
      "percent": 91.7,
      "percentBound": "",
      "lat": 13.892,
      "lon": -60.98
    },
    {
      "name": "St. Vincent and the Grenadines",
      "region": "Latin America-Caribbean",
      "count": 90000,
      "countBelow": false,
      "percent": 86.3,
      "percentBound": "",
      "lat": 13.088,
      "lon": -61.336
    },
    {
      "name": "Sudan",
      "region": "Middle East-North Africa",
      "count": 230000,
      "countBelow": false,
      "percent": 0.5,
      "percentBound": "",
      "lat": 16.331,
      "lon": 29.261
    },
    {
      "name": "Suriname",
      "region": "Latin America-Caribbean",
      "count": 320000,
      "countBelow": false,
      "percent": 52.8,
      "percentBound": "",
      "lat": 4.144,
      "lon": -55.911
    },
    {
      "name": "Sweden",
      "region": "Europe",
      "count": 6290000,
      "countBelow": false,
      "percent": 60.8,
      "percentBound": "",
      "lat": 65.859,
      "lon": 19.017
    },
    {
      "name": "Switzerland",
      "region": "Europe",
      "count": 5320000,
      "countBelow": false,
      "percent": 61.6,
      "percentBound": "",
      "lat": 46.719,
      "lon": 7.464
    },
    {
      "name": "Syria",
      "region": "Middle East-North Africa",
      "count": 810000,
      "countBelow": false,
      "percent": 3.8,
      "percentBound": "",
      "lat": 35.007,
      "lon": 38.278
    },
    {
      "name": "Taiwan",
      "region": "Asia-Pacific",
      "count": 1310000,
      "countBelow": false,
      "percent": 5.5,
      "percentBound": "",
      "lat": 23.652,
      "lon": 120.868
    },
    {
      "name": "Tajikistan",
      "region": "Asia-Pacific",
      "count": 100000,
      "countBelow": false,
      "percent": 1,
      "percentBound": "",
      "lat": 38.2,
      "lon": 72.587
    },
    {
      "name": "Tanzania",
      "region": "Sub-Saharan Africa",
      "count": 39440000,
      "countBelow": false,
      "percent": 64.7,
      "percentBound": "",
      "lat": -6.052,
      "lon": 34.959
    },
    {
      "name": "Thailand",
      "region": "Asia-Pacific",
      "count": 740000,
      "countBelow": false,
      "percent": 1,
      "percentBound": "",
      "lat": 15.46,
      "lon": 101.073
    },
    {
      "name": "Timor-Leste",
      "region": "Asia-Pacific",
      "count": 1320000,
      "countBelow": false,
      "percent": 99.5,
      "percentBound": "",
      "lat": -8.804,
      "lon": 125.855
    },
    {
      "name": "Togo",
      "region": "Sub-Saharan Africa",
      "count": 4930000,
      "countBelow": false,
      "percent": 56.9,
      "percentBound": "",
      "lat": 8.807,
      "lon": 1.058
    },
    {
      "name": "Tonga",
      "region": "Asia-Pacific",
      "count": 100000,
      "countBelow": false,
      "percent": 97.8,
      "percentBound": "",
      "lat": -21.21,
      "lon": -175.163
    },
    {
      "name": "Trinidad and Tobago",
      "region": "Latin America-Caribbean",
      "count": 1040000,
      "countBelow": false,
      "percent": 70,
      "percentBound": "",
      "lat": 10.999,
      "lon": -60.918
    },
    {
      "name": "Tunisia",
      "region": "Middle East-North Africa",
      "count": 30000,
      "countBelow": false,
      "percent": 0.2,
      "percentBound": "",
      "lat": 33.687,
      "lon": 9.008
    },
    {
      "name": "Turkey",
      "region": "Asia-Pacific",
      "count": 120000,
      "countBelow": false,
      "percent": 0.1,
      "percentBound": "",
      "lat": 39.345,
      "lon": 34.508
    },
    {
      "name": "Turkmenistan",
      "region": "Asia-Pacific",
      "count": 390000,
      "countBelow": false,
      "percent": 5.6,
      "percentBound": "",
      "lat": 39.855,
      "lon": 58.677
    },
    {
      "name": "U.S. Virgin Islands",
      "region": "Latin America-Caribbean",
      "count": 80000,
      "countBelow": false,
      "percent": 94.5,
      "percentBound": "",
      "lat": 17.747,
      "lon": -64.779
    },
    {
      "name": "Uganda",
      "region": "Sub-Saharan Africa",
      "count": 39010000,
      "countBelow": false,
      "percent": 87.7,
      "percentBound": "",
      "lat": 1.973,
      "lon": 32.949
    },
    {
      "name": "Ukraine",
      "region": "Europe",
      "count": 37280000,
      "countBelow": false,
      "percent": 83.4,
      "percentBound": "",
      "lat": 49.725,
      "lon": 32.141
    },
    {
      "name": "United Arab Emirates",
      "region": "Middle East-North Africa",
      "count": 1350000,
      "countBelow": false,
      "percent": 14.3,
      "percentBound": "",
      "lat": 23.466,
      "lon": 54.547
    },
    {
      "name": "United Kingdom",
      "region": "Europe",
      "count": 33250000,
      "countBelow": false,
      "percent": 49.4,
      "percentBound": "",
      "lat": 54.403,
      "lon": -2.116
    },
    {
      "name": "United States",
      "region": "North America",
      "count": 217270000,
      "countBelow": false,
      "percent": 64,
      "percentBound": "",
      "lat": 39.538,
      "lon": -97.483
    },
    {
      "name": "Uruguay",
      "region": "Latin America-Caribbean",
      "count": 1510000,
      "countBelow": false,
      "percent": 44.5,
      "percentBound": "",
      "lat": -32.961,
      "lon": -55.967
    },
    {
      "name": "Uzbekistan",
      "region": "Asia-Pacific",
      "count": 930000,
      "countBelow": false,
      "percent": 2.8,
      "percentBound": "",
      "lat": 41.694,
      "lon": 64.005
    },
    {
      "name": "Vanuatu",
      "region": "Asia-Pacific",
      "count": 250000,
      "countBelow": false,
      "percent": 83.5,
      "percentBound": "",
      "lat": -15.372,
      "lon": 166.909
    },
    {
      "name": "Venezuela",
      "region": "Latin America-Caribbean",
      "count": 25060000,
      "countBelow": false,
      "percent": 88.1,
      "percentBound": "",
      "lat": 7.182,
      "lon": -64.599
    },
    {
      "name": "Vietnam",
      "region": "Asia-Pacific",
      "count": 8170000,
      "countBelow": false,
      "percent": 8.3,
      "percentBound": "",
      "lat": 21.715,
      "lon": 105.387
    },
    {
      "name": "Western Sahara",
      "region": "Middle East-North Africa",
      "count": 10000,
      "countBelow": true,
      "percent": 0.2,
      "percentBound": "",
      "lat": 23.968,
      "lon": -12.63
    },
    {
      "name": "Yemen",
      "region": "Middle East-North Africa",
      "count": 20000,
      "countBelow": false,
      "percent": 0.1,
      "percentBound": "<",
      "lat": 15.328,
      "lon": 45.874
    },
    {
      "name": "Zambia",
      "region": "Sub-Saharan Africa",
      "count": 18730000,
      "countBelow": false,
      "percent": 98.3,
      "percentBound": "",
      "lat": -14.661,
      "lon": 26.395
    },
    {
      "name": "Zimbabwe",
      "region": "Sub-Saharan Africa",
      "count": 13540000,
      "countBelow": false,
      "percent": 87.2,
      "percentBound": "",
      "lat": -18.912,
      "lon": 29.925
    }
  ]
};
